# Generated by Django 5.2.7 on 2025-10-22 21:31

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('swapi_id', models.IntegerField(help_text='ID from SWAPI', unique=True)),
                ('title', models.CharField(max_length=255)),
                ('episode_id', models.IntegerField()),
                ('opening_crawl', models.TextField()),
                ('director', models.CharField(max_length=255)),
                ('producer', models.CharField(max_length=255)),
                ('release_date', models.DateField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['release_date'],
                'indexes': [models.Index(fields=['release_date'], name='api_film_release_e198a1_idx'), models.Index(fields=['swapi_id'], name='api_film_swapi_i_dcc07c_idx')],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Comment text (max 500 characters)', max_length=500, validators=[django.core.validators.MaxLengthValidator(500)])),
                ('author_name', models.CharField(default='Anonymous', help_text='Name of the commenter', max_length=100)),
                ('author_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='api.film')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['film', 'created_at'], name='api_comment_film_id_84d8d3_idx')],
            },
        ),
    ]
